made changes to extend datamodel with additional properties
smart-data-models/dataModel.DCAT-AP pull request #2
Opened 2023-06-05 07:16 UTC by marendtz

2023-06-05 09:31 UTC, albertoabellagarcia requested changes
Change the examples according to the notes in the example.json (but the other formats have to be changed as well)

2023-06-05 09:31 UTC, albertoabellagarcia commented on DataServiceDCAT-AP/examples/example_extended-normalized.json
The name of the file cannot be changed, so please rename example-normalized.json

2023-06-05 09:31 UTC, albertoabellagarcia commented on DataServiceDCAT-AP/examples/example_extended.json
> +{
name of the file has to be kept

2023-06-05 09:31 UTC, albertoabellagarcia commented on DataServiceDCAT-AP/examples/example_extended.jsonld
> +{
keep the name of the file

2023-06-05 09:31 UTC, albertoabellagarcia commented on DataServiceDCAT-AP/examples/example_extended.json
> +  "dataServiceDescription": "Service that crawls web documents for a specific NGSI-LD entity of the type Organization (https://smartdatamodels.org/dataModel.Organization/Organization)",
it should be an array (change example o schema)

2023-06-05 09:31 UTC, albertoabellagarcia commented on DataServiceDCAT-AP/examples/example_extended.json
> +  "title": "AgendaAnalyticsCrawling",
It has to be an array not a string

2023-06-05 09:31 UTC, albertoabellagarcia commented on DataServiceDCAT-AP/examples/example_extended.json
> +  "endpointURL": "https://www.crawling-service.com",
it has to be an array not a string

2023-06-05 09:59 UTC, marendtz commented
> Change the examples according to the notes in the example.json (but the other formats have to be changed as well)

Do you want me to overwrite all the examples with the examples of the extended use case? Or should I adapt the existing examples with exemplary values for the added attributes? This may be complicated, because the examples use case of the EDP may not have e.g. an assetProvider.

2023-06-06 07:31 UTC, albertoabellagarcia commented
> > Change the examples according to the notes in the example.json (but the other formats have to be changed as well)
> 
> Do you want me to overwrite all the examples with the examples of the extended use case? Or should I adapt the existing examples with exemplary values for the added attributes? This may be complicated, because the examples use case of the EDP may not have e.g. an assetProvider.

Yes you have to rewrite the examples with the extended attributes (in the 4 formats). Ideally you can just add the extended attributes to existing examples. If you want to change the values of other attributes is also possible. What you should not do is to remove attributes from the examples. 
And to check that the keyvalues examples are validated by the schema. We use this [tool](https://www.jsonschemavalidator.net/) for this validation but you can use whatever you want.

2023-06-08 16:40 UTC, albertoabellagarcia approved these changes

2023-06-08 16:40 UTC, merged